#!/bin/sh

mv manifest.json manifest.bak
cat manifest.bak | awk '! /update_url/ { print $0 }' > manifest.json
7z a ../metabot.zip manifest.json metabot.js bot_accounts.js _locales
mv manifest.bak manifest.json

# repack crx-extension
cd ..
echo "Make CRX"
chromium --pack-extension=metabot --pack-extension-key=metabot.pem
mv metabot.crx metabot
echo "https://chrome.google.com/webstore/developer/edit/johgopighfejmkgpcdpabglafmbckgio"
